// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cusum_acc_time_lin_r_t_piecewise_non_traditional
NumericMatrix cusum_acc_time_lin_r_t_piecewise_non_traditional(arma::vec partition_t_vec, arma::vec baseline_vec, double start_year, arma::vec age_vec, arma::vec gender_vec, arma::mat x_matrix, arma::vec time_obs_vec, arma::vec arrival_time_vec, arma::vec delta_i_vec, arma::vec beta_vec, double k, arma::vec t_grid, arma::mat pop_data_male, arma::mat pop_data_female, int end_year_table);
RcppExport SEXP _CUSUMrelsurv_cusum_acc_time_lin_r_t_piecewise_non_traditional(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP start_yearSEXP, SEXP age_vecSEXP, SEXP gender_vecSEXP, SEXP x_matrixSEXP, SEXP time_obs_vecSEXP, SEXP arrival_time_vecSEXP, SEXP delta_i_vecSEXP, SEXP beta_vecSEXP, SEXP kSEXP, SEXP t_gridSEXP, SEXP pop_data_maleSEXP, SEXP pop_data_femaleSEXP, SEXP end_year_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< double >::type start_year(start_yearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type age_vec(age_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gender_vec(gender_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_matrix(x_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_obs_vec(time_obs_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_i_vec(delta_i_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_grid(t_gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_male(pop_data_maleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_female(pop_data_femaleSEXP);
    Rcpp::traits::input_parameter< int >::type end_year_table(end_year_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(cusum_acc_time_lin_r_t_piecewise_non_traditional(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, k, t_grid, pop_data_male, pop_data_female, end_year_table));
    return rcpp_result_gen;
END_RCPP
}
// cusum_acc_time_lin_r_t_piecewise_traditional
NumericMatrix cusum_acc_time_lin_r_t_piecewise_traditional(arma::vec partition_t_vec, arma::vec baseline_vec, double start_year, arma::vec age_vec, arma::vec gender_vec, arma::mat x_matrix, arma::vec time_obs_vec, arma::vec arrival_time_vec, arma::vec delta_i_vec, arma::vec beta_vec, double k, arma::vec t_grid, arma::mat pop_data_male, arma::mat pop_data_female, int end_year_table);
RcppExport SEXP _CUSUMrelsurv_cusum_acc_time_lin_r_t_piecewise_traditional(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP start_yearSEXP, SEXP age_vecSEXP, SEXP gender_vecSEXP, SEXP x_matrixSEXP, SEXP time_obs_vecSEXP, SEXP arrival_time_vecSEXP, SEXP delta_i_vecSEXP, SEXP beta_vecSEXP, SEXP kSEXP, SEXP t_gridSEXP, SEXP pop_data_maleSEXP, SEXP pop_data_femaleSEXP, SEXP end_year_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< double >::type start_year(start_yearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type age_vec(age_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gender_vec(gender_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_matrix(x_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_obs_vec(time_obs_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_i_vec(delta_i_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_grid(t_gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_male(pop_data_maleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_female(pop_data_femaleSEXP);
    Rcpp::traits::input_parameter< int >::type end_year_table(end_year_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(cusum_acc_time_lin_r_t_piecewise_traditional(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, k, t_grid, pop_data_male, pop_data_female, end_year_table));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_acc_time_lin_piecewise_in_and_out_non_traditional
arma::vec vec_excess_sim_acc_time_lin_piecewise_in_and_out_non_traditional(arma::vec& partition_t_vec, arma::vec& baseline_vec, arma::vec& max_follow_up_vec, arma::vec& u_vec, arma::vec& arrival_time_vec, arma::vec& linear_predictor_vec, double k, double eta);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_in_and_out_non_traditional(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP max_follow_up_vecSEXP, SEXP u_vecSEXP, SEXP arrival_time_vecSEXP, SEXP linear_predictor_vecSEXP, SEXP kSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_acc_time_lin_piecewise_in_and_out_non_traditional(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, k, eta));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_acc_time_lin_piecewise_in_and_out_traditional
arma::vec vec_excess_sim_acc_time_lin_piecewise_in_and_out_traditional(arma::vec& partition_t_vec, arma::vec& baseline_vec, arma::vec& max_follow_up_vec, arma::vec& u_vec, arma::vec& arrival_time_vec, arma::vec& linear_predictor_vec, double k, double eta);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_in_and_out_traditional(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP max_follow_up_vecSEXP, SEXP u_vecSEXP, SEXP arrival_time_vecSEXP, SEXP linear_predictor_vecSEXP, SEXP kSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_acc_time_lin_piecewise_in_and_out_traditional(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, k, eta));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_acc_time_lin_piecewise_out_non_traditional
arma::vec vec_excess_sim_acc_time_lin_piecewise_out_non_traditional(arma::vec& partition_t_vec, arma::vec& baseline_vec, arma::vec& max_follow_up_vec, arma::vec& u_vec, arma::vec& linear_predictor_vec, double k);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_out_non_traditional(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP max_follow_up_vecSEXP, SEXP u_vecSEXP, SEXP linear_predictor_vecSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_acc_time_lin_piecewise_out_non_traditional(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, k));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_acc_time_lin_piecewise_out_traditional
arma::vec vec_excess_sim_acc_time_lin_piecewise_out_traditional(arma::vec& partition_t_vec, arma::vec& baseline_vec, arma::vec& max_follow_up_vec, arma::vec& u_vec, arma::vec& linear_predictor_vec, double k);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_out_traditional(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP max_follow_up_vecSEXP, SEXP u_vecSEXP, SEXP linear_predictor_vecSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_acc_time_lin_piecewise_out_traditional(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, k));
    return rcpp_result_gen;
END_RCPP
}
// cusum_add_approx_r_t_piecewise
NumericMatrix cusum_add_approx_r_t_piecewise(arma::vec partition_t_vec, arma::vec baseline_vec, double start_year, arma::vec age_vec, arma::vec gender_vec, arma::mat x_matrix, arma::vec time_obs_vec, arma::vec arrival_time_vec, arma::vec delta_i_vec, arma::vec beta_vec, double gamma, arma::vec t_grid, arma::mat pop_data_male, arma::mat pop_data_female, int end_year_table);
RcppExport SEXP _CUSUMrelsurv_cusum_add_approx_r_t_piecewise(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP start_yearSEXP, SEXP age_vecSEXP, SEXP gender_vecSEXP, SEXP x_matrixSEXP, SEXP time_obs_vecSEXP, SEXP arrival_time_vecSEXP, SEXP delta_i_vecSEXP, SEXP beta_vecSEXP, SEXP gammaSEXP, SEXP t_gridSEXP, SEXP pop_data_maleSEXP, SEXP pop_data_femaleSEXP, SEXP end_year_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< double >::type start_year(start_yearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type age_vec(age_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gender_vec(gender_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_matrix(x_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_obs_vec(time_obs_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_i_vec(delta_i_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_grid(t_gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_male(pop_data_maleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_female(pop_data_femaleSEXP);
    Rcpp::traits::input_parameter< int >::type end_year_table(end_year_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(cusum_add_approx_r_t_piecewise(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table));
    return rcpp_result_gen;
END_RCPP
}
// cusum_add_exact_r_t_piecewise
NumericMatrix cusum_add_exact_r_t_piecewise(arma::vec partition_t_vec, arma::vec baseline_vec, double start_year, arma::vec age_vec, arma::vec gender_vec, arma::mat x_matrix, arma::vec time_obs_vec, arma::vec arrival_time_vec, arma::vec delta_i_vec, arma::vec beta_vec, double gamma, arma::vec t_grid, arma::mat pop_data_male, arma::mat pop_data_female, int end_year_table);
RcppExport SEXP _CUSUMrelsurv_cusum_add_exact_r_t_piecewise(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP start_yearSEXP, SEXP age_vecSEXP, SEXP gender_vecSEXP, SEXP x_matrixSEXP, SEXP time_obs_vecSEXP, SEXP arrival_time_vecSEXP, SEXP delta_i_vecSEXP, SEXP beta_vecSEXP, SEXP gammaSEXP, SEXP t_gridSEXP, SEXP pop_data_maleSEXP, SEXP pop_data_femaleSEXP, SEXP end_year_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< double >::type start_year(start_yearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type age_vec(age_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gender_vec(gender_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_matrix(x_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_obs_vec(time_obs_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_i_vec(delta_i_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_grid(t_gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_male(pop_data_maleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_female(pop_data_femaleSEXP);
    Rcpp::traits::input_parameter< int >::type end_year_table(end_year_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(cusum_add_exact_r_t_piecewise(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table));
    return rcpp_result_gen;
END_RCPP
}
// cusum_add_excess_non_neg_r_t_piecewise
NumericMatrix cusum_add_excess_non_neg_r_t_piecewise(arma::vec partition_t_vec, arma::vec baseline_vec, double start_year, arma::vec age_vec, arma::vec gender_vec, arma::mat x_matrix, arma::vec time_obs_vec, arma::vec arrival_time_vec, arma::vec delta_i_vec, arma::vec beta_vec, double gamma, arma::vec t_grid, arma::mat pop_data_male, arma::mat pop_data_female, int end_year_table);
RcppExport SEXP _CUSUMrelsurv_cusum_add_excess_non_neg_r_t_piecewise(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP start_yearSEXP, SEXP age_vecSEXP, SEXP gender_vecSEXP, SEXP x_matrixSEXP, SEXP time_obs_vecSEXP, SEXP arrival_time_vecSEXP, SEXP delta_i_vecSEXP, SEXP beta_vecSEXP, SEXP gammaSEXP, SEXP t_gridSEXP, SEXP pop_data_maleSEXP, SEXP pop_data_femaleSEXP, SEXP end_year_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< double >::type start_year(start_yearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type age_vec(age_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gender_vec(gender_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_matrix(x_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_obs_vec(time_obs_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_i_vec(delta_i_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_grid(t_gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_male(pop_data_maleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_female(pop_data_femaleSEXP);
    Rcpp::traits::input_parameter< int >::type end_year_table(end_year_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(cusum_add_excess_non_neg_r_t_piecewise(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_add_excess_non_neg_piecewise_in_and_out
arma::vec vec_excess_sim_add_excess_non_neg_piecewise_in_and_out(arma::vec& partition_t_vec, arma::vec& baseline_vec, arma::vec& max_follow_up_vec, arma::vec& u_vec, arma::vec& arrival_time_vec, arma::vec& linear_predictor_vec, double gamma, double eta);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_add_excess_non_neg_piecewise_in_and_out(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP max_follow_up_vecSEXP, SEXP u_vecSEXP, SEXP arrival_time_vecSEXP, SEXP linear_predictor_vecSEXP, SEXP gammaSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_add_excess_non_neg_piecewise_in_and_out(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, gamma, eta));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_add_excess_non_neg_piecewise_out
arma::vec vec_excess_sim_add_excess_non_neg_piecewise_out(arma::vec& partition_t_vec, arma::vec& baseline_vec, arma::vec& max_follow_up_vec, arma::vec& u_vec, arma::vec& linear_predictor_vec, double gamma);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_add_excess_non_neg_piecewise_out(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP max_follow_up_vecSEXP, SEXP u_vecSEXP, SEXP linear_predictor_vecSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_add_excess_non_neg_piecewise_out(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, gamma));
    return rcpp_result_gen;
END_RCPP
}
// cusum_add_total_haz_non_neg_exact_r_t_piecewise
NumericMatrix cusum_add_total_haz_non_neg_exact_r_t_piecewise(arma::vec partition_t_vec, arma::vec baseline_vec, double start_year, arma::vec age_vec, arma::vec gender_vec, arma::mat x_matrix, arma::vec time_obs_vec, arma::vec arrival_time_vec, arma::vec delta_i_vec, arma::vec beta_vec, double gamma, arma::vec t_grid, arma::mat pop_data_male, arma::mat pop_data_female, int end_year_table);
RcppExport SEXP _CUSUMrelsurv_cusum_add_total_haz_non_neg_exact_r_t_piecewise(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP start_yearSEXP, SEXP age_vecSEXP, SEXP gender_vecSEXP, SEXP x_matrixSEXP, SEXP time_obs_vecSEXP, SEXP arrival_time_vecSEXP, SEXP delta_i_vecSEXP, SEXP beta_vecSEXP, SEXP gammaSEXP, SEXP t_gridSEXP, SEXP pop_data_maleSEXP, SEXP pop_data_femaleSEXP, SEXP end_year_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< double >::type start_year(start_yearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type age_vec(age_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gender_vec(gender_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_matrix(x_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_obs_vec(time_obs_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_i_vec(delta_i_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_grid(t_gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_male(pop_data_maleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_female(pop_data_femaleSEXP);
    Rcpp::traits::input_parameter< int >::type end_year_table(end_year_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(cusum_add_total_haz_non_neg_exact_r_t_piecewise(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_EM
arma::vec vec_excess_sim_EM(Rcpp::Function predict_cumulative_baseline_haz_general_func, double min_cumulative_baseline_event_time, arma::vec& u_vec, arma::vec& linear_predictor_vec, arma::vec& max_follow_up_vec);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_EM(SEXP predict_cumulative_baseline_haz_general_funcSEXP, SEXP min_cumulative_baseline_event_timeSEXP, SEXP u_vecSEXP, SEXP linear_predictor_vecSEXP, SEXP max_follow_up_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type predict_cumulative_baseline_haz_general_func(predict_cumulative_baseline_haz_general_funcSEXP);
    Rcpp::traits::input_parameter< double >::type min_cumulative_baseline_event_time(min_cumulative_baseline_event_timeSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_EM(predict_cumulative_baseline_haz_general_func, min_cumulative_baseline_event_time, u_vec, linear_predictor_vec, max_follow_up_vec));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_piecewise
arma::vec vec_excess_sim_piecewise(arma::vec& partition_t_vec, arma::vec& baseline_vec, arma::vec& max_follow_up_vec, arma::vec& u_vec, arma::vec& linear_predictor_vec);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_piecewise(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP max_follow_up_vecSEXP, SEXP u_vecSEXP, SEXP linear_predictor_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_piecewise(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec));
    return rcpp_result_gen;
END_RCPP
}
// vec_pop_sim
arma::mat vec_pop_sim(arma::vec& age_vec, arma::vec& gender_vec, double& start_year, double& end_year, double& table_end_year, arma::vec& arrival_time_vec, arma::mat& pop_matrix_male, arma::mat& pop_matrix_female, arma::vec& u);
RcppExport SEXP _CUSUMrelsurv_vec_pop_sim(SEXP age_vecSEXP, SEXP gender_vecSEXP, SEXP start_yearSEXP, SEXP end_yearSEXP, SEXP table_end_yearSEXP, SEXP arrival_time_vecSEXP, SEXP pop_matrix_maleSEXP, SEXP pop_matrix_femaleSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type age_vec(age_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type gender_vec(gender_vecSEXP);
    Rcpp::traits::input_parameter< double& >::type start_year(start_yearSEXP);
    Rcpp::traits::input_parameter< double& >::type end_year(end_yearSEXP);
    Rcpp::traits::input_parameter< double& >::type table_end_year(table_end_yearSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type pop_matrix_male(pop_matrix_maleSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type pop_matrix_female(pop_matrix_femaleSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_pop_sim(age_vec, gender_vec, start_year, end_year, table_end_year, arrival_time_vec, pop_matrix_male, pop_matrix_female, u));
    return rcpp_result_gen;
END_RCPP
}
// cusum_prop_r_t_EM_smoothing_spline
NumericMatrix cusum_prop_r_t_EM_smoothing_spline(Rcpp::Function cumulative_baseline_haz_vec_general_func, Rcpp::Function baseline_haz_vec_general_func, double start_year, arma::vec age_vec, arma::vec gender_vec, arma::mat x_matrix, arma::vec time_obs_vec, arma::vec arrival_time_vec, arma::vec delta_i_vec, arma::vec beta_vec, double rho, arma::vec t_grid, arma::mat pop_data_male, arma::mat pop_data_female, int end_year_table);
RcppExport SEXP _CUSUMrelsurv_cusum_prop_r_t_EM_smoothing_spline(SEXP cumulative_baseline_haz_vec_general_funcSEXP, SEXP baseline_haz_vec_general_funcSEXP, SEXP start_yearSEXP, SEXP age_vecSEXP, SEXP gender_vecSEXP, SEXP x_matrixSEXP, SEXP time_obs_vecSEXP, SEXP arrival_time_vecSEXP, SEXP delta_i_vecSEXP, SEXP beta_vecSEXP, SEXP rhoSEXP, SEXP t_gridSEXP, SEXP pop_data_maleSEXP, SEXP pop_data_femaleSEXP, SEXP end_year_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type cumulative_baseline_haz_vec_general_func(cumulative_baseline_haz_vec_general_funcSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type baseline_haz_vec_general_func(baseline_haz_vec_general_funcSEXP);
    Rcpp::traits::input_parameter< double >::type start_year(start_yearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type age_vec(age_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gender_vec(gender_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_matrix(x_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_obs_vec(time_obs_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_i_vec(delta_i_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_grid(t_gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_male(pop_data_maleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_female(pop_data_femaleSEXP);
    Rcpp::traits::input_parameter< int >::type end_year_table(end_year_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(cusum_prop_r_t_EM_smoothing_spline(cumulative_baseline_haz_vec_general_func, baseline_haz_vec_general_func, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, rho, t_grid, pop_data_male, pop_data_female, end_year_table));
    return rcpp_result_gen;
END_RCPP
}
// cusum_prop_r_t_piecewise
NumericMatrix cusum_prop_r_t_piecewise(arma::vec partition_t_vec, arma::vec baseline_vec, double start_year, arma::vec age_vec, arma::vec gender_vec, arma::mat x_matrix, arma::vec time_obs_vec, arma::vec arrival_time_vec, arma::vec delta_i_vec, arma::vec beta_vec, double rho, arma::vec t_grid, arma::mat pop_data_male, arma::mat pop_data_female, int end_year_table);
RcppExport SEXP _CUSUMrelsurv_cusum_prop_r_t_piecewise(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP start_yearSEXP, SEXP age_vecSEXP, SEXP gender_vecSEXP, SEXP x_matrixSEXP, SEXP time_obs_vecSEXP, SEXP arrival_time_vecSEXP, SEXP delta_i_vecSEXP, SEXP beta_vecSEXP, SEXP rhoSEXP, SEXP t_gridSEXP, SEXP pop_data_maleSEXP, SEXP pop_data_femaleSEXP, SEXP end_year_tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< double >::type start_year(start_yearSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type age_vec(age_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gender_vec(gender_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_matrix(x_matrixSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_obs_vec(time_obs_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_i_vec(delta_i_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_vec(beta_vecSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type t_grid(t_gridSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_male(pop_data_maleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pop_data_female(pop_data_femaleSEXP);
    Rcpp::traits::input_parameter< int >::type end_year_table(end_year_tableSEXP);
    rcpp_result_gen = Rcpp::wrap(cusum_prop_r_t_piecewise(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, rho, t_grid, pop_data_male, pop_data_female, end_year_table));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_prop_piecewise_in_and_out
arma::vec vec_excess_sim_prop_piecewise_in_and_out(arma::vec& partition_t_vec, arma::vec& baseline_vec, arma::vec& max_follow_up_vec, arma::vec& u_vec, arma::vec& arrival_time_vec, arma::vec& linear_predictor_vec, double rho, double eta);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_prop_piecewise_in_and_out(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP max_follow_up_vecSEXP, SEXP u_vecSEXP, SEXP arrival_time_vecSEXP, SEXP linear_predictor_vecSEXP, SEXP rhoSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type arrival_time_vec(arrival_time_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_prop_piecewise_in_and_out(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, rho, eta));
    return rcpp_result_gen;
END_RCPP
}
// vec_excess_sim_prop_piecewise_out
arma::vec vec_excess_sim_prop_piecewise_out(arma::vec& partition_t_vec, arma::vec& baseline_vec, arma::vec& max_follow_up_vec, arma::vec& u_vec, arma::vec& linear_predictor_vec, double rho);
RcppExport SEXP _CUSUMrelsurv_vec_excess_sim_prop_piecewise_out(SEXP partition_t_vecSEXP, SEXP baseline_vecSEXP, SEXP max_follow_up_vecSEXP, SEXP u_vecSEXP, SEXP linear_predictor_vecSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type partition_t_vec(partition_t_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type baseline_vec(baseline_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type max_follow_up_vec(max_follow_up_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type u_vec(u_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type linear_predictor_vec(linear_predictor_vecSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_excess_sim_prop_piecewise_out(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CUSUMrelsurv_cusum_acc_time_lin_r_t_piecewise_non_traditional", (DL_FUNC) &_CUSUMrelsurv_cusum_acc_time_lin_r_t_piecewise_non_traditional, 15},
    {"_CUSUMrelsurv_cusum_acc_time_lin_r_t_piecewise_traditional", (DL_FUNC) &_CUSUMrelsurv_cusum_acc_time_lin_r_t_piecewise_traditional, 15},
    {"_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_in_and_out_non_traditional", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_in_and_out_non_traditional, 8},
    {"_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_in_and_out_traditional", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_in_and_out_traditional, 8},
    {"_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_out_non_traditional", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_out_non_traditional, 6},
    {"_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_out_traditional", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_out_traditional, 6},
    {"_CUSUMrelsurv_cusum_add_approx_r_t_piecewise", (DL_FUNC) &_CUSUMrelsurv_cusum_add_approx_r_t_piecewise, 15},
    {"_CUSUMrelsurv_cusum_add_exact_r_t_piecewise", (DL_FUNC) &_CUSUMrelsurv_cusum_add_exact_r_t_piecewise, 15},
    {"_CUSUMrelsurv_cusum_add_excess_non_neg_r_t_piecewise", (DL_FUNC) &_CUSUMrelsurv_cusum_add_excess_non_neg_r_t_piecewise, 15},
    {"_CUSUMrelsurv_vec_excess_sim_add_excess_non_neg_piecewise_in_and_out", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_add_excess_non_neg_piecewise_in_and_out, 8},
    {"_CUSUMrelsurv_vec_excess_sim_add_excess_non_neg_piecewise_out", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_add_excess_non_neg_piecewise_out, 6},
    {"_CUSUMrelsurv_cusum_add_total_haz_non_neg_exact_r_t_piecewise", (DL_FUNC) &_CUSUMrelsurv_cusum_add_total_haz_non_neg_exact_r_t_piecewise, 15},
    {"_CUSUMrelsurv_vec_excess_sim_EM", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_EM, 5},
    {"_CUSUMrelsurv_vec_excess_sim_piecewise", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_piecewise, 5},
    {"_CUSUMrelsurv_vec_pop_sim", (DL_FUNC) &_CUSUMrelsurv_vec_pop_sim, 9},
    {"_CUSUMrelsurv_cusum_prop_r_t_EM_smoothing_spline", (DL_FUNC) &_CUSUMrelsurv_cusum_prop_r_t_EM_smoothing_spline, 15},
    {"_CUSUMrelsurv_cusum_prop_r_t_piecewise", (DL_FUNC) &_CUSUMrelsurv_cusum_prop_r_t_piecewise, 15},
    {"_CUSUMrelsurv_vec_excess_sim_prop_piecewise_in_and_out", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_prop_piecewise_in_and_out, 8},
    {"_CUSUMrelsurv_vec_excess_sim_prop_piecewise_out", (DL_FUNC) &_CUSUMrelsurv_vec_excess_sim_prop_piecewise_out, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_CUSUMrelsurv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
