# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function to calculate the CUSUM chart at different time points given by t_grid
#' 
#' Function to calculate the CUSUM chart at different time points given by t_grid using linear accelerated time alternative
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param start_year Calendar year of when the monitoring starts. End year is implicitly defined via t_grid. 
#' @param age_vec A vector containing age of the observations when they arrive in the study. 
#' @param gender_vec A vector containing gender indicator - 1 for male, 2 for female. 
#' @param x_matrix A matrix containing the predictor variables (need to contain the same amount of columns as the dimension of beta_vec, the estimated parameter vector).
#' @param time_obs_vec A vector containing the observed time of the observations. 
#' @param arrival_time_vec A vector containing the amount of time units after start year the observations arrive. Should be less than or equal to max(t_grid).
#' @param delta_i_vec A vector containing the event indicator at the end of follow-up. 
#' @param beta_vec A vector containing the estimated parameters from the model related to the predictor variables.
#' @param k Linear time acceleration factor for the out-of-control hazard model. 
#' @param t_grid The time grid to calculate the CUSUM chart. 
#' @param pop_data_male A matrix of population table for male. Should follow the matrix format with first column being the year, second column being age and third column being the hazard values.
#' @param pop_data_female Similar as above, but for female. 
#' @param end_year_table The last calendar year appearing in the population table. 
#' @return final_result_matrix A matrix where the first column is the chart value, the second column counts the number of events.
#' @export
cusum_acc_time_lin_r_t_piecewise_non_traditional <- function(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, k, t_grid, pop_data_male, pop_data_female, end_year_table) {
    .Call(`_CUSUMrelsurv_cusum_acc_time_lin_r_t_piecewise_non_traditional`, partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, k, t_grid, pop_data_male, pop_data_female, end_year_table)
}

#' Function to calculate the CUSUM chart at different time points given by t_grid
#' 
#' Function to calculate the CUSUM chart at different time points given by t_grid using linear accelerated time alternative
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param start_year Calendar year of when the monitoring starts. End year is implicitly defined via t_grid. 
#' @param age_vec A vector containing age of the observations when they arrive in the study. 
#' @param gender_vec A vector containing gender indicator - 1 for male, 2 for female. 
#' @param x_matrix A matrix containing the predictor variables (need to contain the same amount of columns as the dimension of beta_vec, the estimated parameter vector).
#' @param time_obs_vec A vector containing the observed time of the observations. 
#' @param arrival_time_vec A vector containing the amount of time units after start year the observations arrive. Should be less than or equal to max(t_grid).
#' @param delta_i_vec A vector containing the event indicator at the end of follow-up. 
#' @param beta_vec A vector containing the estimated parameters from the model related to the predictor variables.
#' @param k Linear time acceleration factor for the out-of-control hazard model. 
#' @param t_grid The time grid to calculate the CUSUM chart. 
#' @param pop_data_male A matrix of population table for male. Should follow the matrix format with first column being the year, second column being age and third column being the hazard values.
#' @param pop_data_female Similar as above, but for female. 
#' @param end_year_table The last calendar year appearing in the population table. 
#' @return final_result_matrix A matrix where the first column is the chart value, the second column counts the number of events.
#' @export
cusum_acc_time_lin_r_t_piecewise_traditional <- function(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, k, t_grid, pop_data_male, pop_data_female, end_year_table) {
    .Call(`_CUSUMrelsurv_cusum_acc_time_lin_r_t_piecewise_traditional`, partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, k, t_grid, pop_data_male, pop_data_female, end_year_table)
}

#' Function to simulate excess times during a time period where the hazard switches from in-control to out-of-control
#' 
#' Function to simulate excess times during a time period where the hazard switches from in-control to out-of-control using linear accelerated time alternative
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param arrival_time_vec A vector corresponding to the arrival time after the start of monitoring of the observations. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param k Linear time acceleration factor for the out-of-control hazard model. 
#' @param eta The time point after monitoring start where the hazard switches to the out-of-control. 
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations.  
#' @export
vec_excess_sim_acc_time_lin_piecewise_in_and_out_non_traditional <- function(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, k, eta) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_in_and_out_non_traditional`, partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, k, eta)
}

#' Function to simulate excess times during a time period where the hazard switches from in-control to out-of-control
#' 
#' Function to simulate excess times during a time period where the hazard switches from in-control to out-of-control using linear accelerated time alternative
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param arrival_time_vec A vector corresponding to the arrival time after the start of monitoring of the observations. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param k Linear time acceleration factor for the out-of-control hazard model. 
#' @param eta The time point after monitoring start where the hazard switches to the out-of-control. 
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations.  
#' @export
vec_excess_sim_acc_time_lin_piecewise_in_and_out_traditional <- function(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, k, eta) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_in_and_out_traditional`, partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, k, eta)
}

#' Function to simulate excess times during a time period where the hazard starts in out-of-control
#' 
#' Function to simulate excess times during a time period where the hazard starts in out-of-control using linear accelerated time alternative
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param k Linear time acceleration factor for the out-of-control hazard model. 
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations.  
#' @export
vec_excess_sim_acc_time_lin_piecewise_out_non_traditional <- function(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, k) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_out_non_traditional`, partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, k)
}

#' Function to simulate excess times during a time period where the hazard starts in out-of-control
#' 
#' Function to simulate excess times during a time period where the hazard starts in out-of-control using linear accelerated time alternative
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param k Linear time acceleration factor for the out-of-control hazard model. 
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations.  
#' @export
vec_excess_sim_acc_time_lin_piecewise_out_traditional <- function(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, k) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_acc_time_lin_piecewise_out_traditional`, partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, k)
}

#' Function to calculate the CUSUM chart at different time points given by t_grid
#' 
#' Function to calculate the CUSUM chart at different time points given by t_grid using additive alternative (approximated by first order Taylor expansion)
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param start_year Calendar year of when the monitoring starts. End year is implicitly defined via t_grid. 
#' @param age_vec A vector containing age of the observations when they arrive in the study. 
#' @param gender_vec A vector containing gender indicator - 1 for male, 2 for female. 
#' @param x_matrix A matrix containing the predictor variables (need to contain the same amount of columns as the dimension of beta_vec, the estimated parameter vector).
#' @param time_obs_vec A vector containing the observed time of the observations. 
#' @param arrival_time_vec A vector containing the amount of time units after start year the observations arrive. Should be less than or equal to max(t_grid).
#' @param delta_i_vec A vector containing the event indicator at the end of follow-up. 
#' @param beta_vec A vector containing the estimated parameters from the model related to the predictor variables.
#' @param gamma Additive constant for the out-of-control hazard model. 
#' @param t_grid The time grid to calculate the CUSUM chart. 
#' @param pop_data_male A matrix of population table for male. Should follow the matrix format with first column being the year, second column being age and third column being the hazard values.
#' @param pop_data_female Similar as above, but for female. 
#' @param end_year_table The last calendar year appearing in the population table. 
#' @return final_result_matrix A matrix where the first column is the chart value, the second column counts the number of events.
#' @export
cusum_add_approx_r_t_piecewise <- function(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table) {
    .Call(`_CUSUMrelsurv_cusum_add_approx_r_t_piecewise`, partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table)
}

#' Function to calculate the CUSUM chart at different time points given by t_grid
#' 
#' Function to calculate the CUSUM chart at different time points given by t_grid using (exact) additive alternative
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param start_year Calendar year of when the monitoring starts. End year is implicitly defined via t_grid. 
#' @param age_vec A vector containing age of the observations when they arrive in the study. 
#' @param gender_vec A vector containing gender indicator - 1 for male, 2 for female. 
#' @param x_matrix A matrix containing the predictor variables (need to contain the same amount of columns as the dimension of beta_vec, the estimated parameter vector).
#' @param time_obs_vec A vector containing the observed time of the observations. 
#' @param arrival_time_vec A vector containing the amount of time units after start year the observations arrive. Should be less than or equal to max(t_grid).
#' @param delta_i_vec A vector containing the event indicator at the end of follow-up. 
#' @param beta_vec A vector containing the estimated parameters from the model related to the predictor variables.
#' @param gamma Additive constant for the out-of-control hazard model. 
#' @param t_grid The time grid to calculate the CUSUM chart. 
#' @param pop_data_male A matrix of population table for male. Should follow the matrix format with first column being the year, second column being age and third column being the hazard values.
#' @param pop_data_female Similar as above, but for female. 
#' @param end_year_table The last calendar year appearing in the population table. 
#' @return final_result_matrix A matrix where the first column is the chart value, the second column counts the number of events.
#' @export
cusum_add_exact_r_t_piecewise <- function(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table) {
    .Call(`_CUSUMrelsurv_cusum_add_exact_r_t_piecewise`, partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table)
}

#' Function to calculate the CUSUM chart at different time points given by t_grid
#' 
#' Function to calculate the CUSUM chart at different time points given by t_grid using additive alternative, assuming non-negative excess hazard
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param start_year Calendar year of when the monitoring starts. End year is implicitly defined via t_grid. 
#' @param age_vec A vector containing age of the observations when they arrive in the study. 
#' @param gender_vec A vector containing gender indicator - 1 for male, 2 for female. 
#' @param x_matrix A matrix containing the predictor variables (need to contain the same amount of columns as the dimension of beta_vec, the estimated parameter vector).
#' @param time_obs_vec A vector containing the observed time of the observations. 
#' @param arrival_time_vec A vector containing the amount of time units after start year the observations arrive. Should be less than or equal to max(t_grid).
#' @param delta_i_vec A vector containing the event indicator at the end of follow-up. 
#' @param beta_vec A vector containing the estimated parameters from the model related to the predictor variables.
#' @param gamma Additive constant for the out-of-control hazard model. 
#' @param t_grid The time grid to calculate the CUSUM chart. 
#' @param pop_data_male A matrix of population table for male. Should follow the matrix format with first column being the year, second column being age and third column being the hazard values.
#' @param pop_data_female Similar as above, but for female. 
#' @param end_year_table The last calendar year appearing in the population table. 
#' @return final_result_matrix A matrix where the first column is the chart value, the second column counts the number of events.
#' @export
cusum_add_excess_non_neg_r_t_piecewise <- function(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table) {
    .Call(`_CUSUMrelsurv_cusum_add_excess_non_neg_r_t_piecewise`, partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table)
}

#' Function to simulate excess times during a time period where the hazard switches from in-control to out-of-control
#' 
#' Function to simulate excess times during a time period where the hazard switches from in-control to out-of-control using additive alternative, assuming non-negative excess hazard
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param arrival_time_vec A vector corresponding to the arrival time after the start of monitoring of the observations. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param gamma Additive constant for the out-of-control hazard model.
#' @param eta The time point after monitoring start where the hazard switches to the out-of-control. 
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations.  
#' @export
vec_excess_sim_add_excess_non_neg_piecewise_in_and_out <- function(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, gamma, eta) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_add_excess_non_neg_piecewise_in_and_out`, partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, gamma, eta)
}

#' Function to simulate excess times during a time period where the hazard starts in out-of-control
#' 
#' Function to simulate excess times during a time period where the hazard starts in out-of-control using additive alternative, assuming non-negative excess hazard
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param gamma Additive constant for the out-of-control hazard model.
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations.  
#' @export 
vec_excess_sim_add_excess_non_neg_piecewise_out <- function(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, gamma) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_add_excess_non_neg_piecewise_out`, partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, gamma)
}

#' Function to calculate the CUSUM chart at different time points given by t_grid
#' 
#' Function to calculate the CUSUM chart at different time points given by t_grid using additive alternative (assuming non-negative overall/total hazard)
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param start_year Calendar year of when the monitoring starts. End year is implicitly defined via t_grid. 
#' @param age_vec A vector containing age of the observations when they arrive in the study. 
#' @param gender_vec A vector containing gender indicator - 1 for male, 2 for female. 
#' @param x_matrix A matrix containing the predictor variables (need to contain the same amount of columns as the dimension of beta_vec, the estimated parameter vector).
#' @param time_obs_vec A vector containing the observed time of the observations. 
#' @param arrival_time_vec A vector containing the amount of time units after start year the observations arrive. Should be less than or equal to max(t_grid).
#' @param delta_i_vec A vector containing the event indicator at the end of follow-up. 
#' @param beta_vec A vector containing the estimated parameters from the model related to the predictor variables.
#' @param gamma Additive constant for the out-of-control hazard model. 
#' @param t_grid The time grid to calculate the CUSUM chart. 
#' @param pop_data_male A matrix of population table for male. Should follow the matrix format with first column being the year, second column being age and third column being the hazard values.
#' @param pop_data_female Similar as above, but for female. 
#' @param end_year_table The last calendar year appearing in the population table. 
#' @return final_result_matrix A matrix where the first column is the chart value, the second column counts the number of events.
#' @export
cusum_add_total_haz_non_neg_exact_r_t_piecewise <- function(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table) {
    .Call(`_CUSUMrelsurv_cusum_add_total_haz_non_neg_exact_r_t_piecewise`, partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, gamma, t_grid, pop_data_male, pop_data_female, end_year_table)
}

#' Function to simulate excess times based on output from semi-parametric (EM) excess hazard model
#' 
#' Function to simulate excess times based on output from semi-parametric (EM) excess hazard model
#' @param predict_cumulative_baseline_haz_general_func A function that returns predicted value of cumulative baseline based on the smoothed estimated from the EM output from relsurv.
#' @param min_cumulative_baseline_event_time The smallest time to event that was used in the semi-parametric model for estimation.
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations.  
#' @export
vec_excess_sim_EM <- function(predict_cumulative_baseline_haz_general_func, min_cumulative_baseline_event_time, u_vec, linear_predictor_vec, max_follow_up_vec) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_EM`, predict_cumulative_baseline_haz_general_func, min_cumulative_baseline_event_time, u_vec, linear_predictor_vec, max_follow_up_vec)
}

#' Function to simulate excess times based on output from piecewise constant baseline excess hazard model
#' 
#' Function to simulate excess times based on output from piecewise constant baseline excess hazard model
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations.  
#' @export
vec_excess_sim_piecewise <- function(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_piecewise`, partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec)
}

#' Function to simulate population times based on life tables
#' 
#' Function to simulate population times based on life tables
#' @param age_vec A vector containing age of the observations when they arrive in the study. 
#' @param gender_vec A vector containing gender indicator - 0 for male, 1 for female. 
#' @param start_year Calendar year of when the monitoring starts. 
#' @param end_year Calendar year of when the monitoring ends. 
#' @param table_end_year The last calendar year appearing in the population table. 
#' @param arrival_time_vec A vector containing the amount of time units after start year the observations arrive.
#' @param pop_matrix_male Population table for male, should be a matrix with first column corresponding to year, second column to age and third column to the population hazard value. 
#' @param pop_matrix_female Population table for female, should be a matrix with first column corresponding to year, second column to age and third column to the population hazard value. 
#' @param u A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @return A matrix where first column corresponds to the population time and the second is the event indicator. 
#' @export
vec_pop_sim <- function(age_vec, gender_vec, start_year, end_year, table_end_year, arrival_time_vec, pop_matrix_male, pop_matrix_female, u) {
    .Call(`_CUSUMrelsurv_vec_pop_sim`, age_vec, gender_vec, start_year, end_year, table_end_year, arrival_time_vec, pop_matrix_male, pop_matrix_female, u)
}

#' Function to calculate the CUSUM chart at different time points given by t_grid
#' 
#' Function to calculate the CUSUM chart at different time points given by t_grid using proportional alternative with output from rsadd(..., method = "EM") as baseline hazard
#' 
#' @param cumulative_baseline_haz_vec_general_func R function that corresponds to the estimated cumulative baseline hazard obtained by the excess hazard model based on EM algorithm.
#' @param baseline_haz_vec_general_func R function that corresponds to the estimated baseline hazard obtained by the excess hazard model based on EM algorithm.
#' @param start_year Calendar year of when the monitoring starts. End year is implicitly defined via t_grid. 
#' @param age_vec A vector containing age of the observations when they arrive in the study. 
#' @param gender_vec A vector containing gender indicator - 1 for male, 2 for female. 
#' @param x_matrix A matrix containing the predictor variables (need to contain the same amount of columns as the dimension of beta_vec, the estimated parameter vector).
#' @param time_obs_vec A vector containing the observed time of the observations. 
#' @param arrival_time_vec A vector containing the amount of time units after start year the observations arrive. Should be less than or equal to max(t_grid).
#' @param delta_i_vec A vector containing the event indicator at the end of follow-up. 
#' @param beta_vec A vector containing the estimated parameters from the model related to the predictor variables.
#' @param rho Proportional constant for the out-of-control hazard model.  
#' @param t_grid The time grid to calculate the CUSUM chart. 
#' @param pop_data_male A matrix of population table for male. Should follow the matrix format with first column being the year, second column being age and third column being the hazard values.
#' @param pop_data_female Similar as above, but for female. 
#' @param end_year_table The last calendar year appearing in the population table. 
#' @return final_result_matrix A matrix where the first column is the chart value, the second column counts the number of events.
#' @export
cusum_prop_r_t_EM_smoothing_spline <- function(cumulative_baseline_haz_vec_general_func, baseline_haz_vec_general_func, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, rho, t_grid, pop_data_male, pop_data_female, end_year_table) {
    .Call(`_CUSUMrelsurv_cusum_prop_r_t_EM_smoothing_spline`, cumulative_baseline_haz_vec_general_func, baseline_haz_vec_general_func, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, rho, t_grid, pop_data_male, pop_data_female, end_year_table)
}

#' Function to calculate the CUSUM chart at different time points given by t_grid
#' 
#' Function to calculate the CUSUM chart at different time points given by t_grid using proportional alternative with piecewise constant baseline hazard. 
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param start_year Calendar year of when the monitoring starts. End year is implicitly defined via t_grid. 
#' @param age_vec A vector containing age of the observations when they arrive in the study. 
#' @param gender_vec A vector containing gender indicator - 1 for male, 2 for female. 
#' @param x_matrix A matrix containing the predictor variables (need to contain the same amount of columns as the dimension of beta_vec, the estimated parameter vector).
#' @param time_obs_vec A vector containing the observed time of the observations. 
#' @param arrival_time_vec A vector containing the amount of time units after start year the observations arrive. Should be less than or equal to max(t_grid).
#' @param delta_i_vec A vector containing the event indicator at the end of follow-up. 
#' @param beta_vec A vector containing the estimated parameters from the model related to the predictor variables.
#' @param rho Proportional constant for the out-of-control hazard model.  
#' @param t_grid The time grid to calculate the CUSUM chart. 
#' @param pop_data_male A matrix of population table for male. Should follow the matrix format with first column being the year, second column being age and third column being the hazard values.
#' @param pop_data_female Similar as above, but for female. 
#' @param end_year_table The last calendar year appearing in the population table. 
#' @return final_result_matrix A matrix where the first column is the chart value, the second column counts the number of events.
#' @export
cusum_prop_r_t_piecewise <- function(partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, rho, t_grid, pop_data_male, pop_data_female, end_year_table) {
    .Call(`_CUSUMrelsurv_cusum_prop_r_t_piecewise`, partition_t_vec, baseline_vec, start_year, age_vec, gender_vec, x_matrix, time_obs_vec, arrival_time_vec, delta_i_vec, beta_vec, rho, t_grid, pop_data_male, pop_data_female, end_year_table)
}

#' Function to simulate excess times during a time period where the hazard switches from in-control to out-of-control
#' 
#' Function to simulate excess times during a time period where the hazard switches from in-control to out-of-control using proportional alternative
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param arrival_time_vec A vector corresponding to the arrival time after the start of monitoring of the observations. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param rho Proportional constant for the out-of-control hazard model. 
#' @param eta The time point after monitoring start where the hazard switches to the out-of-control. 
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations. 
#' @export
vec_excess_sim_prop_piecewise_in_and_out <- function(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, rho, eta) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_prop_piecewise_in_and_out`, partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, arrival_time_vec, linear_predictor_vec, rho, eta)
}

#' Function to simulate excess times during a time period where the hazard starts in out-of-control
#' 
#' Function to simulate excess times during a time period where the hazard starts in out-of-control using proportional alternative
#' 
#' @param partition_t_vec A vector that defines the partition of the time period for the piecewise constant baseline hazard.
#' @param baseline_vec A vector of baseline hazard values defined over the time partition. 
#' @param max_follow_up_vec A vector corresponding to the max follow up times of the observations.  
#' @param u_vec A vector of samples from Unif(0, 1) for inverse transform algorithm. 
#' @param linear_predictor_vec the matrix vector product of the covariate matrix and the regression coefficients. 
#' @param rho Proportional constant for the out-of-control hazard model. 
#' @return time_excess_sim A vector of simulated excess times based on the input of the observations.  
#' @export 
vec_excess_sim_prop_piecewise_out <- function(partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, rho) {
    .Call(`_CUSUMrelsurv_vec_excess_sim_prop_piecewise_out`, partition_t_vec, baseline_vec, max_follow_up_vec, u_vec, linear_predictor_vec, rho)
}

